[build]
  publish = "_book"
  command = "yarn docs:build"

# Redirect requests to domain aliases to the primary domain.

[[redirects]]
  from = "https://neutrino.js.org/*"
  to = "https://neutrinojs.org/:splat"
  force = true

[[redirects]]
  from = "https://neutrinojs.netlify.com/*"
  to = "https://neutrinojs.org/:splat"
  force = true
